import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
await mkdir('notes/qa', { recursive: true });
const results = [];
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
  await page.locator('#start-folders-root:not([hidden])').waitFor();
  await page.locator('.start-sec').scrollIntoViewIfNeeded();
  await page.waitForTimeout(1800);
  assert.equal(await page.locator('.folder-float').count(), 4);
  const oldLinks = await page.locator('#start-cards-fallback a').evaluateAll(nodes => nodes.map(n => n.getAttribute('href')));
  const newLinks = await page.locator('.start-folder-link').evaluateAll(nodes => nodes.map(n => n.getAttribute('href')));
  assert.deepEqual(newLinks, oldLinks);
  await page.locator('.start-sec').screenshot({ path: 'notes/qa/folders-desktop.png' });
  const desktopHeight = await page.locator('.start-sec').evaluate(el => el.getBoundingClientRect().height);
  assert.ok(desktopHeight < 710, 'Desktop section stays compact');
  results.push('Desktop section height: ' + Math.round(desktopHeight) + 'px.');
  const first = page.locator('.folder-float').first();
  await first.hover();
  await page.waitForTimeout(1000);
  assert.equal(await first.getAttribute('data-live'), '');
  assert.equal(await first.locator('.folder-float__trigger').getAttribute('aria-expanded'), 'true');
  await page.locator('.start-sec').screenshot({ path: 'notes/qa/folders-open.png' });
  const pill = first.locator('.folder-float__item').first();
  const box = await pill.boundingBox();
  await page.mouse.move(box.x + box.width/2, box.y + box.height/2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width/2 + 18, box.y + box.height/2 - 10, { steps: 5 });
  assert.equal(await pill.getAttribute('data-drag'), '');
  await page.mouse.up();
  assert.equal(page.url(), 'http://localhost:3000/');
  await first.locator('.folder-float__trigger').focus();
  await page.keyboard.press('Tab');
  assert.equal(await pill.evaluate(el => el === document.activeElement), true);
  await page.keyboard.press('Escape');
  assert.equal(await first.locator('.folder-float__trigger').getAttribute('aria-expanded'), 'false');
  assert.equal(await first.locator('.folder-float__trigger').evaluate(el => el === document.activeElement), true);
  results.push('Desktop: four folders, original destinations, hover physics, drag without navigation, Tab and Escape passed.');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await first.locator('.folder-float__trigger').press('Enter');
  await page.waitForTimeout(900);
  assert.equal(await first.getAttribute('data-open'), '');
  assert.equal(await first.getAttribute('data-live'), null);
  results.push('Reduced motion: choices open with physics disabled.');
  for (const width of [768, 390, 320]) {
    const mobile = await browser.newPage({ viewport: { width, height: 900 }, hasTouch: true, isMobile: true });
    mobile.on('pageerror', error => errors.push(error.message));
    await mobile.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
    await mobile.locator('#start-folders-root:not([hidden])').waitFor();
    await mobile.locator('.start-sec').scrollIntoViewIfNeeded();
    await mobile.waitForTimeout(1200);
    const closedHeight = await mobile.locator('.start-sec').evaluate(el => el.getBoundingClientRect().height);
    const columns = await mobile.locator('.start-folders-grid').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length);
    assert.equal(columns, 2);
    assert.ok(closedHeight < 820, 'Mobile section stays compact');
    await mobile.locator('.start-sec').screenshot({ path: 'notes/qa/folders-closed-' + width + '.png' });
    results.push(width + 'px: two columns, collapsed section ' + Math.round(closedHeight) + 'px.');
    const folder = mobile.locator('.folder-float').first();
    await folder.locator('.folder-float__trigger').tap();
    await mobile.waitForTimeout(850);
    assert.equal(await folder.getAttribute('data-open'), '');
    assert.equal(await folder.getAttribute('data-live'), '');
    const sectionBounds = await mobile.locator('.start-sec').boundingBox();
    const floatingBounds = await folder.locator('.folder-float__item').first().boundingBox();
    assert.ok(floatingBounds.y >= sectionBounds.y, 'Floating pills stay inside the mobile section');
    assert.ok(floatingBounds.y < await folder.locator('.folder-float__trigger').evaluate(el => el.getBoundingClientRect().top), 'Mobile choices float above the folder');
    const overflows = await folder.locator('.folder-float__item').evaluateAll(nodes => nodes.some(n => { const r=n.getBoundingClientRect(); return r.left<0 || r.right>innerWidth; }));
    assert.equal(overflows, false);
    await mobile.waitForTimeout(200);
    assert.equal(await folder.getAttribute('data-live'), '', 'Physics stays active while choices are open');
    const smallTargets = await folder.locator('.folder-float__item').evaluateAll(nodes => nodes.some(n => n.getBoundingClientRect().height < 44));
    assert.equal(smallTargets, false);
    const second = mobile.locator('.folder-float').nth(1);
    await second.locator('.folder-float__trigger').tap();
    assert.equal(await folder.getAttribute('data-open'), null);
    assert.equal(await second.getAttribute('data-open'), '');
    await folder.locator('.folder-float__trigger').tap();
    await mobile.locator('.start-sec').screenshot({ path: 'notes/qa/folders-' + width + '.png' });
    await folder.locator('.folder-float__trigger').tap();
    assert.equal(await folder.getAttribute('data-open'), null);
    results.push(width + 'px: touch open/close and floating choices fit viewport.');
    await mobile.close();
  }
  const nojs = await browser.newPage({ javaScriptEnabled: false });
  await nojs.goto('http://localhost:3000');
  assert.equal(await nojs.locator('#start-cards-fallback a').count(),4);
  assert.equal(await nojs.locator('#start-cards-fallback').getAttribute('hidden'),null);
  results.push('Original HTML links retained without React/JavaScript.');
  assert.deepEqual(errors, []);
  results.push('No browser JavaScript errors.');
  console.log(results.join('\n'));
  await writeFile('notes/qa/results.txt', results.join('\n'));
} finally { await browser.close(); }
